# Generated by Django 5.1.2 on 2024-11-19 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strategyapp', '0002_tweet1_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='tweet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='strategyapp.tweet'),
        ),
        migrations.DeleteModel(
            name='Tweet1',
        ),
    ]
